# Generated by Django 4.1.7 on 2023-03-05 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('budget', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenditurecategory',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.household'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.expenditurecategory'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.household'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
