# Generated by Django 4.1.7 on 2023-03-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('budget', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='for_who',
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.household')),
            ],
        ),
        migrations.AddField(
            model_name='expenditure',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.beneficiary'),
        ),
    ]
